### ISSUE TITLE
Many green lines

### ISSUE THREAD

**Issue by BannStrider** [thatshaman/ReShadeShaders#2]
Not sure if this an issue or a self-bug, but tried renaming dxgi and d3d11, with old and new chromakey and cannot make my character on a chroma background. As soon as I place near plane to 0.1 almost all screen goes green, also there's so many green (or RGB selected chroma) lines around. Pasting some screens to explain what's happening.

Far plane 0.1
![0 1farplane](https://github.com/user-attachments/assets/a3574b42-70c7-4ab3-84ce-dfb76cd70bfd)

Near plane 0.1
![0 1nearplane](https://github.com/user-attachments/assets/e24978ef-16ea-4766-821a-4b378fef0bb1)

Default
![chromakey_default](https://github.com/user-attachments/assets/66d87697-116a-4de1-84b1-34e8453b23c1)

Method : Never
![nevermethod](https://github.com/user-attachments/assets/cfa488c4-8e8c-46a7-bd4d-0eca75d71220)

**Comment by BannStrider** [comment]
Forgot to add ReShade 6.2.0 (no add-ons)

**Comment by thatshaman** [comment]
- I've just updated the readme file, you need to set the `Preprocessor Definitions` to the values shown there order to fix the far plane issues
- The near plane should generally not be changed (only if you want to cull out things close to the camera)
- You should only enable the "remove flat surfaces" option when you're standing on totally flat terrain, otherwise make sure it is set to none
